#!/usr/bin/env julia
using Oscar

const ROOT = normpath(joinpath(@__DIR__, ".."))
const DATA_DIR = joinpath(ROOT, "data")
const GROUP_ID = "groups"

struct ExampleSpec
    title::String
    body::String
    code::String
end

function description_md(title::String, body::String)
    return "---\ntitle: $(title)\ngroup: groups\n---\n\n# $(title)\n\n$(body)\n"
end

examples = ExampleSpec[
    ExampleSpec("Symmetric group element", "A generator of the symmetric group S_5.", """
G = symmetric_group(5)
obj = gen(G, 1)
"""),
    ExampleSpec("Symmetric group", "The full symmetric group S_5.", """
obj = symmetric_group(5)
"""),
    ExampleSpec("Sylow subgroup of symmetric group", "A Sylow-2 subgroup of S_5.", """
G = symmetric_group(5)
obj = sylow_subgroup(G, 2)[1]
"""),
    ExampleSpec("Element of Sylow subgroup", "A generator of a Sylow-2 subgroup of S_5.", """
G = symmetric_group(5)
U = sylow_subgroup(G, 2)[1]
obj = gen(U, 1)
"""),
    ExampleSpec("Tuple with permutation groups", "Tuple `(x, y, G, U)` with elements and ambient permutation groups.", """
G = symmetric_group(5)
x = gen(G, 1)
U = sylow_subgroup(G, 2)[1]
y = gen(U, 1)
obj = (x, y, G, U)
"""),
    ExampleSpec("Tuple of permutation elements", "Tuple `(x, x^2, y)` with elements from two permutation groups.", """
G = symmetric_group(5)
x = gen(G, 1)
U = sylow_subgroup(G, 2)[1]
y = gen(U, 1)
obj = (x, x^2, y)
"""),
    ExampleSpec("Free group element", "A generator of a rank-2 free group.", """
F = free_group(2)
obj = gen(F, 1)
"""),
    ExampleSpec("Free group", "The free group of rank 2.", """
obj = free_group(2)
"""),
    ExampleSpec("Subgroup of free group", "Subgroup generated by the first generator in a free group.", """
F = free_group(2)
obj = sub(F, [gen(F, 1)])[1]
"""),
    ExampleSpec("Element of free subgroup", "A generator of a subgroup of a free group.", """
F = free_group(2)
U = sub(F, [gen(F, 1)])[1]
obj = gen(U, 1)
"""),
    ExampleSpec("Tuple with free groups", "Tuple `(x, y, F, U)` with free-group elements and groups.", """
F = free_group(2)
x = gen(F, 1)
U = sub(F, [gen(F, 1)])[1]
y = gen(U, 1)
obj = (x, y, F, U)
"""),
    ExampleSpec("Tuple of free-group elements", "Tuple `(x, x^2, y)` with elements from two free groups.", """
F = free_group(2)
x = gen(F, 1)
U = sub(F, [gen(F, 1)])[1]
y = gen(U, 1)
obj = (x, x^2, y)
"""),
    ExampleSpec("Free abelian group", "A free abelian group of rank 2.", """
obj = free_abelian_group(2)
"""),
    ExampleSpec("Homomorphism of free abelian groups", "A homomorphism from rank-2 to rank-3 free abelian group defined by an integer matrix.", """
dom = free_abelian_group(2)
codom = free_abelian_group(3)
mat = matrix(ZZ, [[1, 2, 3], [2, 3, 4]])
obj = hom(dom, codom, mat)
"""),
    ExampleSpec("Element of finitely presented group", "A generator in a finitely presented quotient of a free group.", """
F = free_group(2)
x1 = gen(F, 1)
x2 = gen(F, 2)
G = quo(F, [x1^2, x2^2, comm(x1, x2)])[1]
obj = gen(G, 1)
"""),
    ExampleSpec("Finitely presented group", "A quotient of a free group by involution and commutator relations.", """
F = free_group(2)
x1 = gen(F, 1)
x2 = gen(F, 2)
obj = quo(F, [x1^2, x2^2, comm(x1, x2)])[1]
"""),
    ExampleSpec("Subgroup of finitely presented group", "A subgroup generated by the first generator of a finitely presented group.", """
F = free_group(2)
x1 = gen(F, 1)
x2 = gen(F, 2)
G = quo(F, [x1^2, x2^2, comm(x1, x2)])[1]
obj = sub(G, [gen(G, 1)])[1]
"""),
    ExampleSpec("Element of subgroup of finitely presented group", "A generator of a subgroup inside a finitely presented group.", """
F = free_group(2)
x1 = gen(F, 1)
x2 = gen(F, 2)
G = quo(F, [x1^2, x2^2, comm(x1, x2)])[1]
U = sub(G, [gen(G, 1)])[1]
obj = gen(U, 1)
"""),
    ExampleSpec("Tuple with finitely presented groups", "Tuple `(x, y, G, U)` with elements and groups in the finitely presented setting.", """
F = free_group(2)
x1 = gen(F, 1)
x2 = gen(F, 2)
G = quo(F, [x1^2, x2^2, comm(x1, x2)])[1]
x = gen(G, 1)
U = sub(G, [gen(G, 1)])[1]
y = gen(U, 1)
obj = (x, y, G, U)
"""),
    ExampleSpec("Tuple of finitely presented group elements", "Tuple `(x, x^2, y)` with elements from a finitely presented group and its subgroup.", """
F = free_group(2)
x1 = gen(F, 1)
x2 = gen(F, 2)
G = quo(F, [x1^2, x2^2, comm(x1, x2)])[1]
x = gen(G, 1)
U = sub(G, [gen(G, 1)])[1]
y = gen(U, 1)
obj = (x, x^2, y)
"""),
    ExampleSpec("Element of pc group", "An element from the small group `(24, 12)`.", """
G = small_group(24, 12)
obj = gen(G, 1)
"""),
    ExampleSpec("Pc group", "The small group identified by `(24, 12)`.", """
obj = small_group(24, 12)
"""),
    ExampleSpec("Sylow subgroup of pc group", "A Sylow-2 subgroup of the small group `(24, 12)`.", """
G = small_group(24, 12)
obj = sylow_subgroup(G, 2)[1]
"""),
    ExampleSpec("Element of Sylow subgroup of pc group", "A generator of a Sylow-2 subgroup in a pc group.", """
G = small_group(24, 12)
U = sylow_subgroup(G, 2)[1]
obj = gen(U, 1)
"""),
    ExampleSpec("Tuple with pc groups", "Tuple `(x, y, G, U)` with pc-group elements and groups.", """
G = small_group(24, 12)
x = gen(G, 1)
U = sylow_subgroup(G, 2)[1]
y = gen(U, 1)
obj = (x, y, G, U)
"""),
    ExampleSpec("Tuple of pc-group elements", "Tuple `(x, x^2, y)` with elements from a pc group and its Sylow subgroup.", """
G = small_group(24, 12)
x = gen(G, 1)
U = sylow_subgroup(G, 2)[1]
y = gen(U, 1)
obj = (x, x^2, y)
"""),
    ExampleSpec("Product of generators in matrix group", "Product of all generators of `GL(3, 5)`.", """
G = general_linear_group(3, 5)
obj = reduce(*, gens(G))
"""),
    ExampleSpec("Matrix-group elements", "Two elements of `GL(3, 5)` obtained from explicit matrices.", """
G = general_linear_group(3, 5)
mats = [[0 -1 0; 1 -1 0; 0 0 1], [0 1 0; 1 0 0; 0 0 1]]
matelms = map(m -> matrix(GF(5), m), mats)
obj = map(m -> G(m), matelms)
""")
]

function slugify(s::String)
    return String(strip(replace(lowercase(s), r"[^a-z0-9]+" => "-"), '-'))
end


function write_example_files(spec::ExampleSpec, slug::String)
    example_root = joinpath(DATA_DIR, GROUP_ID, slug)
    desc_path = joinpath(example_root, "description.md")
    sys_path = joinpath(example_root, "systems", "Oscar.jl")
    mkpath(sys_path)

    write(desc_path, description_md(spec.title, spec.body))

    generate_path = joinpath(sys_path, "generate.jl")
    generate_code = "using Oscar\n\n" * strip(spec.code) * "\n\nsave(\"data.json\", obj)\n"
    write(generate_path, generate_code)

    return slug, sys_path
end

function build_object(code::String)
    expr = Meta.parse("begin\n" * code * "\nobj\nend")
    return Core.eval(Main, expr)
end

seen_slugs = Dict{String, Int}()

for spec in examples
    base_slug = slugify(spec.title)
    count = get!(seen_slugs, base_slug, 0) + 1
    seen_slugs[base_slug] = count
    slug = count == 1 ? base_slug : string(base_slug, "-", count)

    exname, sys_path = write_example_files(spec, slug)
    obj = build_object(spec.code)
    save(joinpath(sys_path, "data.json"), obj)
    println("Generated ", exname)
end
