#!/usr/bin/env julia
using Oscar

const ROOT = normpath(joinpath(@__DIR__, ".."))
const DESC_DIR = joinpath(ROOT, "example_descriptions")
const OSCAR_DIR = joinpath(ROOT, "systems", "Oscar.jl")

struct ExampleSpec
    number::Int
    title::String
    body::String
    code::String
end

function description_md(title::String, body::String)
    return "---\ntitle: $(title)\ngroup: groups\n---\n\n# $(title)\n\n$(body)\n"
end

examples = ExampleSpec[
    ExampleSpec(25, "Symmetric group element", "A generator of the symmetric group S_5.", """
G = symmetric_group(5)
obj = gen(G, 1)
"""),
    ExampleSpec(26, "Symmetric group", "The full symmetric group S_5.", """
obj = symmetric_group(5)
"""),
    ExampleSpec(27, "Sylow subgroup of symmetric group", "A Sylow-2 subgroup of S_5.", """
G = symmetric_group(5)
obj = sylow_subgroup(G, 2)[1]
"""),
    ExampleSpec(28, "Element of Sylow subgroup", "A generator of a Sylow-2 subgroup of S_5.", """
G = symmetric_group(5)
U = sylow_subgroup(G, 2)[1]
obj = gen(U, 1)
"""),
    ExampleSpec(29, "Tuple with permutation groups", "Tuple `(x, y, G, U)` with elements and ambient permutation groups.", """
G = symmetric_group(5)
x = gen(G, 1)
U = sylow_subgroup(G, 2)[1]
y = gen(U, 1)
obj = (x, y, G, U)
"""),
    ExampleSpec(30, "Tuple of permutation elements", "Tuple `(x, x^2, y)` with elements from two permutation groups.", """
G = symmetric_group(5)
x = gen(G, 1)
U = sylow_subgroup(G, 2)[1]
y = gen(U, 1)
obj = (x, x^2, y)
"""),
    ExampleSpec(31, "Free group element", "A generator of a rank-2 free group.", """
F = free_group(2)
obj = gen(F, 1)
"""),
    ExampleSpec(32, "Free group", "The free group of rank 2.", """
obj = free_group(2)
"""),
    ExampleSpec(33, "Subgroup of free group", "Subgroup generated by the first generator in a free group.", """
F = free_group(2)
obj = sub(F, [gen(F, 1)])[1]
"""),
    ExampleSpec(34, "Element of free subgroup", "A generator of a subgroup of a free group.", """
F = free_group(2)
U = sub(F, [gen(F, 1)])[1]
obj = gen(U, 1)
"""),
    ExampleSpec(35, "Tuple with free groups", "Tuple `(x, y, F, U)` with free-group elements and groups.", """
F = free_group(2)
x = gen(F, 1)
U = sub(F, [gen(F, 1)])[1]
y = gen(U, 1)
obj = (x, y, F, U)
"""),
    ExampleSpec(36, "Tuple of free-group elements", "Tuple `(x, x^2, y)` with elements from two free groups.", """
F = free_group(2)
x = gen(F, 1)
U = sub(F, [gen(F, 1)])[1]
y = gen(U, 1)
obj = (x, x^2, y)
"""),
    ExampleSpec(37, "Free abelian group", "A free abelian group of rank 2.", """
obj = free_abelian_group(2)
"""),
    ExampleSpec(38, "Homomorphism of free abelian groups", "A homomorphism from rank-2 to rank-3 free abelian group defined by an integer matrix.", """
dom = free_abelian_group(2)
codom = free_abelian_group(3)
mat = matrix(ZZ, [[1, 2, 3], [2, 3, 4]])
obj = hom(dom, codom, mat)
"""),
    ExampleSpec(39, "Element of finitely presented group", "A generator in a finitely presented quotient of a free group.", """
F = free_group(2)
x1 = gen(F, 1)
x2 = gen(F, 2)
G = quo(F, [x1^2, x2^2, comm(x1, x2)])[1]
obj = gen(G, 1)
"""),
    ExampleSpec(40, "Finitely presented group", "A quotient of a free group by involution and commutator relations.", """
F = free_group(2)
x1 = gen(F, 1)
x2 = gen(F, 2)
obj = quo(F, [x1^2, x2^2, comm(x1, x2)])[1]
"""),
    ExampleSpec(41, "Subgroup of finitely presented group", "A subgroup generated by the first generator of a finitely presented group.", """
F = free_group(2)
x1 = gen(F, 1)
x2 = gen(F, 2)
G = quo(F, [x1^2, x2^2, comm(x1, x2)])[1]
obj = sub(G, [gen(G, 1)])[1]
"""),
    ExampleSpec(42, "Element of subgroup of finitely presented group", "A generator of a subgroup inside a finitely presented group.", """
F = free_group(2)
x1 = gen(F, 1)
x2 = gen(F, 2)
G = quo(F, [x1^2, x2^2, comm(x1, x2)])[1]
U = sub(G, [gen(G, 1)])[1]
obj = gen(U, 1)
"""),
    ExampleSpec(43, "Tuple with finitely presented groups", "Tuple `(x, y, G, U)` with elements and groups in the finitely presented setting.", """
F = free_group(2)
x1 = gen(F, 1)
x2 = gen(F, 2)
G = quo(F, [x1^2, x2^2, comm(x1, x2)])[1]
x = gen(G, 1)
U = sub(G, [gen(G, 1)])[1]
y = gen(U, 1)
obj = (x, y, G, U)
"""),
    ExampleSpec(44, "Tuple of finitely presented group elements", "Tuple `(x, x^2, y)` with elements from a finitely presented group and its subgroup.", """
F = free_group(2)
x1 = gen(F, 1)
x2 = gen(F, 2)
G = quo(F, [x1^2, x2^2, comm(x1, x2)])[1]
x = gen(G, 1)
U = sub(G, [gen(G, 1)])[1]
y = gen(U, 1)
obj = (x, x^2, y)
"""),
    ExampleSpec(45, "Element of pc group", "An element from the small group `(24, 12)`.", """
G = small_group(24, 12)
obj = gen(G, 1)
"""),
    ExampleSpec(46, "Pc group", "The small group identified by `(24, 12)`.", """
obj = small_group(24, 12)
"""),
    ExampleSpec(47, "Sylow subgroup of pc group", "A Sylow-2 subgroup of the small group `(24, 12)`.", """
G = small_group(24, 12)
obj = sylow_subgroup(G, 2)[1]
"""),
    ExampleSpec(48, "Element of Sylow subgroup of pc group", "A generator of a Sylow-2 subgroup in a pc group.", """
G = small_group(24, 12)
U = sylow_subgroup(G, 2)[1]
obj = gen(U, 1)
"""),
    ExampleSpec(49, "Tuple with pc groups", "Tuple `(x, y, G, U)` with pc-group elements and groups.", """
G = small_group(24, 12)
x = gen(G, 1)
U = sylow_subgroup(G, 2)[1]
y = gen(U, 1)
obj = (x, y, G, U)
"""),
    ExampleSpec(50, "Tuple of pc-group elements", "Tuple `(x, x^2, y)` with elements from a pc group and its Sylow subgroup.", """
G = small_group(24, 12)
x = gen(G, 1)
U = sylow_subgroup(G, 2)[1]
y = gen(U, 1)
obj = (x, x^2, y)
"""),
    ExampleSpec(51, "Product of generators in matrix group", "Product of all generators of `GL(3, 5)`.", """
G = general_linear_group(3, 5)
obj = reduce(*, gens(G))
"""),
    ExampleSpec(52, "Matrix-group elements", "Two elements of `GL(3, 5)` obtained from explicit matrices.", """
G = general_linear_group(3, 5)
mats = [[0 -1 0; 1 -1 0; 0 0 1], [0 1 0; 1 0 0; 0 0 1]]
matelms = map(m -> matrix(GF(5), m), mats)
obj = map(m -> G(m), matelms)
""")
]

function write_example_files(spec::ExampleSpec)
    exname = "example" * lpad(spec.number, 3, '0')
    desc_path = joinpath(DESC_DIR, exname * ".md")
    sys_path = joinpath(OSCAR_DIR, exname)
    mkpath(sys_path)

    write(desc_path, description_md(spec.title, spec.body))

    generate_path = joinpath(sys_path, "generate.jl")
    generate_code = "using Oscar\n\n" * strip(spec.code) * "\n\nsave(\"data.json\", obj)\n"
    write(generate_path, generate_code)

    return exname, sys_path
end

function build_object(code::String)
    expr = Meta.parse("begin\n" * code * "\nobj\nend")
    return Core.eval(Main, expr)
end

for spec in examples
    exname, sys_path = write_example_files(spec)
    obj = build_object(spec.code)
    save(joinpath(sys_path, "data.json"), obj)
    println("Generated ", exname)
end
